### ISSUE TITLE
The app crashes during search

### ISSUE THREAD

**Issue by Screamir** [LawnchairLauncher/lawnicons#2296] opened 2024-09-04 02:52 UTC
### About this discussion

I wanted to check if there are icons for some games and noticed that when I enter certain combinations, like "bad p" (without quotes), the application crashes.

**Comment by Screamir** [comment] 2024-09-04 02:53
Android 14, Google Pixel 8, icons are already in use at the time of search.

**Comment by SuperDragonXD** [comment] 2024-09-05 01:56
Duplicate of #2258

**Closed by SuperDragonXD** 2024-09-05 01:56 UTC
Labels: discussion
