### ISSUE TITLE
Showing contact app icon instead of dialer app icon

### ISSUE THREAD

**Issue by Rixon46** [LawnchairLauncher/lawnicons#489] opened 2022-05-28 05:29 UTC
link the miui dialer app icon with dialer icon currently its showing contact app icon instead of dialer app icon

**Comment by N0-0NE-Dev** [comment] 2022-07-13 21:51
can you tell me the package name please

**Comment by SuperDragonXD** [comment] 2022-07-19 06:34
(since above didn't work) Duplicate of #462

**Comment by SuperDragonXD** [comment] 2022-07-19 06:34
Duplicate of #462

**Closed by SuperDragonXD** 2022-07-19 06:34 UTC
