### ISSUE TITLE
Add Lawnicons to app drawer

### ISSUE THREAD

**Issue by MarkCyberSecDev93** [LawnchairLauncher/lawnicons#408] opened 2022-02-27 03:25 UTC
It will make apps in app drawer look cleaner! ;)

**Comment by IAmRuMaks** [comment] 2022-02-27 15:52
That has been already suggested: https://github.com/LawnchairLauncher/lawnchair/issues/2337

**Comment by paphonb** [comment] 2022-02-28 13:31
Duplicate of https://github.com/LawnchairLauncher/lawnchair/issues/2425

**Closed by paphonb** 2022-02-28 13:31 UTC
