### ISSUE TITLE
Issue - Search bar is not clickable and off-margin

### ISSUE THREAD

**Issue by imudayveer** [LawnchairLauncher/lawnicons#2495] opened 2024-12-25 03:46 UTC
### About this discussion

Below is the picture of how Lawicons app looks like. As said in subject, the search bar is not clickable.

OS Version - Android 15

Application Version
version 2.12.0
app.lawnchair.lawnicons.play

![Screenshot_20241224-214241](https://github.com/user-attachments/assets/1ce2187f-2319-4da6-b3e5-45c9281579e9)

**Comment by SuperDragonXD** [comment] 2024-12-25 05:59
Interesting. To check, does this happen when you launch the app or do a specific action? The search bar is not supposed to be visible unless you click the search button at the bottom bar.

Can you also reproduce this at the latest nightly?

**Comment by imudayveer** [comment] 2024-12-25 06:24
Same behavior on Nightly version.
version 2.12.0 (Dev #6303)
app.lawnchair.lawnicons

The issue happens on startup. Attached is the video. (Ignore the pixelation, compressed video)

https://github.com/user-attachments/assets/9a0ac443-cc46-4edd-8ea1-028fb32cb8a4

**Comment by imudayveer** [comment] 2024-12-25 06:27
My device is Pixel 9 Pro. My screen width is 426 dp according to Developer Options.

**Comment by SuperDragonXD** [comment] 2024-12-25 07:26
I see. Looks like the larger status bar height showed the ["hidden" search bar](https://github.com/LawnchairLauncher/lawnicons/blob/develop/app%2Fsrc%2Fmain%2Fkotlin%2Fapp%2Flawnchair%2Flawnicons%2Fui%2Fcomponents%2Fhome%2FHomeTopBar.kt#L48) (moving the bar 100px to the top isn't enough ig :D). I will refactor the search bar soon to be located near the bottom, so this issue should be fixed once I've pushed those changes.

**Comment by imudayveer** [comment] 2024-12-25 07:54
Thanks!

**Closed** 2024-12-27 05:43 UTC
Labels: bug, discussion
