### ISSUE TITLE
[BUG] Same Icon For Different Applications

### ISSUE THREAD

**Issue by vaishak97** [LawnchairLauncher/lawnicons#638] opened 2022-08-21 20:18 UTC
### About this discussion

The icons of the Phone app and the Contacts app are the same even after trying to change them manually by long pressing.
![Screenshot_2022-08-22-01-42-39-23_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/57167262/185809252-9e51abe1-7791-40c1-8a7c-30c621b5d071.jpg)

Lawnchair Version: 12.1.0 Alpha 4
OS: Android 12 (OOS12 Open Beta 2)
Device: OnePlus 7 Pro

**Comment by SuperDragonXD** [comment] 2022-08-22 00:44
Duplicate of #636

**Closed by SuperDragonXD** 2022-08-22 00:44 UTC
Labels: discussion
