### ISSUE TITLE
Microsoft Launcher support

### ISSUE THREAD

**Issue by cMonedula** [LawnchairLauncher/lawnicons#372] opened 2022-02-09 17:40 UTC
hello, would it be possible to add basic support for other launchers? just so Lawnicons gets recognized as a proper icon pack, i'd love to use them (but they don't show up in the icon picker menu MS launcher has). or are there any technical caveats that prevent this?

**Comment by SuperDragonXD** [comment] 2022-07-18 13:28
Duplicate of #218

**Closed by SuperDragonXD** 2022-07-18 13:28 UTC
