### ISSUE TITLE
Slack icon is smaller than other icons

### ISSUE THREAD

**Issue by obvionaoe** [LawnchairLauncher/lawnicons#444] opened 2022-04-13 00:59 UTC
The icons for the Slack app and the Aurora Store are smaller than the other icons!
Could this be fixed?

Thanks

**Comment by FPMilan** [comment] 2022-04-23 21:00
Notices the same issue with multiple apps eg, the Teams icon is bigger than other icons.

**Comment by Chefski** [comment] 2022-09-19 13:56
Issue fixed for all 3 icons mentioned

**Comment by FPMilan** [comment] 2022-09-19 14:26
How was this changed? Can you refer to a PR please? Thank you

**Comment by Chefski** [comment] 2022-09-19 14:31
Can't find a PR but each icon is the same size (160x160)
![image](https://user-images.githubusercontent.com/100310118/191042056-800a9d79-6145-4c99-aca6-9d0d006ade89.png)
![image](https://user-images.githubusercontent.com/100310118/191042176-208c82f3-60a1-4fe4-a0a8-0191f9cd1d8b.png)
![image](https://user-images.githubusercontent.com/100310118/191042215-468468e9-3123-4e34-afef-7f3f213228d0.png)

**Comment by FPMilan** [comment] 2022-09-19 14:44
In that view yes I agree, but if you install it it looks like this on your screen. The icon bubbles seam to have different sizes for different icons...
[cid:eu.faircode.email.455]

19.09.2022 16:32:11 Patryk Radziszewski ***@***.***>:

**Comment by FPMilan** [comment] 2022-09-19 14:47
![Screenshot_20220919-164146](https://user-images.githubusercontent.com/10432654/191045809-3b8cb0ff-54b0-4634-a8c0-cae53f1e77ed.png)

**Comment by Chefski** [comment] 2022-09-19 15:20
I'm actually not too sure why that happens. I just checked on my phone now and I only noticed it by cropping it to the border. Not very noticable on my phone.

Someone asked on the Discord why some icons appear bigger and SuperDragin said this: "The icons are scaled to fit the small area, so some icons are bigger while others are smaller"

**Comment by Chefski** [comment] 2022-09-28 19:30
As @obvionaoe said, this issue is caused by the launcher, not the icons.

I'll be closing this & marking the issue as a duplicate as it has already been mentioned in #230

**Closed by Chefski** 2022-09-28 19:30 UTC
Labels: duplicate
